# Site settings
title: Piers Hollott
email: piers.hollott@gmail.com
url: https://phollott.github.io
description: "Personal portfolio for Piers Hollott, including application demonstrators drawn from work in Health Informatics, Open Data, and Open Branding."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 94722b #18bc9c #80B3FF 
  secondary: 82aca0 #2c3e50 #FD6E8A
  secondary-dark: 8c1b1f #233140 #A2122F

# Footer settings
footer:
  copyright: Piers Hollott
  location: Victoria, British Columbia
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/phollott
  - title: github
    url: http://github.com/phollott
  - title: linkedin
    url: https://www.linkedin.com/in/piershollott/en

# Postal address (add as many lines as necessary)
address:
  - line: 5-1850 Fern Street
  - line: Victoria BC, CAN V8R 4K2

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
